### ISSUE TITLE
ReactPoll: Time values >= 10000 as well as non-integer values handled incorrectly

### ISSUE THREAD

**Issue by HelmicNewciv** [flapjax/FlapJack-Cogs#14]
Noninteger values need to be caught with an error message and values for days/weeks/months/indefinitely need to be available as well.

**Comment by flapjax** [comment]
Alright, I remember why I limited poll duration now. The cog uses asyncio.sleep() to wait for the poll to conclude. I was concerned about extraordinarily long sleeps continuing to run after the cog is unloaded.  I've confirmed this is true. This isn't *too* problematic, but it's generally bad programming practice to leave a cog's funtions running after it has been unloaded. I will issue a fix that causes polls to be cancelled when the cog is unloaded. This may take more than a day for me to get to.

**Comment by flapjax** [comment]
With commit https://github.com/flapjax/FlapJack-Cogs/commit/bb49841514eec8705e30a29251a00da70ec18c4b, integers up to 999,999,999,999,999,999 are accepted for poll duration. You may now conduct polls longer than the age of the known universe. Poll tasks are also cancelled on cog unload. As for the non-integers, and day/week/month suggestion, I don't think I am going to add more complex regex detection at this time. Twentysix is currently rewriting Red's built-in poll functions to include reaction polls, so I do not want to spend much effort adding features to this one. You are free to use a duration of several quadrillion seconds if you need an indefinite poll. :D
