### ISSUE TITLE
ColorMe: Color changes always add new role instead of editing existing color role

### ISSUE THREAD

**Issue by HelmicNewciv** [flapjax/FlapJack-Cogs#18]
![image](https://cloud.githubusercontent.com/assets/16701639/24403715/26b290ae-138c-11e7-8fca-b300be15a8c8.png)

oh god why

**Comment by flapjax** [comment]
Usually this means there is a permissions problem or a role hierarchy problem. Make sure that: 

1. Your bot's role is above (meaning literally, on the role hierarchy list) the other users' roles that it is trying to add/edit.

2. Your bot's role has, at minimum, equal permissions to the roles it is trying to add/edit.

If both of these are not true, you will see unexpected behaviors like multiple roles getting created.

**Comment by HelmicNewciv** [comment]
![image](https://cloud.githubusercontent.com/assets/16701639/24408036/9531f19c-139a-11e7-9c3b-486240fd06f7.png)

It's always had both of those things.  It still creates duplicates.

**Comment by flapjax** [comment]
Yeah, that *should* work. Looks like another issue to investigate. In the short term, I will push a hotfix so at least it's not creating duplicate roles.

**Comment by flapjax** [comment]
I pushed some major updates to the error handling, and added a purge command to help you get rid of those extra roles. Let me know if it works out for you.
