### ISSUE TITLE
[blizzard] WoW Token Price broken

### ISSUE THREAD

**Issue by flapjax** [flapjax/FlapJack-Cogs#32]
https://wowtoken.info/ has changed. Token data is hidden until an anti-adblock test is passed. We will need to find a new way/source to obtain token data. Suggestions welcome.

**Comment by therealshibe** [comment]
https://stackoverflow.com/questions/35469540/scraping-using-beautiful-soup-not-working-for-a-particular-url-as-expected

I wonder if the solution here might be the key. Setting a user-agent. 

I'll try to fork+test when I have time.

**Comment by flapjax** [comment]
Fixed thanks to @therealshibe finding a new source.
