### ISSUE TITLE
[blizzard] Error if No Healing done in Competitive Season

### ISSUE THREAD

**Issue by Jademalo** [flapjax/FlapJack-Cogs#33]
If no healing has been done in a competitive season, the following error is thrown;

```[01/05/2017 15:40] ERROR red on_command_error 369: Exception in command 'overwatch stats'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/scotty/Source/Red-DiscordBot/cogs/blizzard.py", line 329, in _stats_overwatch
    '\n**Avg Heal:** ', str(int(round(comp['average_stats']['healing_done_avg'])))])
KeyError: 'healing_done_avg'
```
Using my battle tag (Jademalo#2725) reliably throws this error. Who needs healing anyway =p

**Comment by flapjax** [comment]
Thanks, was able to reproduce! Looks like the API omits the key entirely (possibly because it was 0). Will fix.

**Comment by flapjax** [comment]
Fixed! https://github.com/flapjax/FlapJack-Cogs/commit/e0b8f0d70ac6da8fab9ed8c7c07a5d475f9fb466

Please update your cog and let me know if you encounter further problems.
