### ISSUE TITLE
[Blizzard] delete embedded patch notes after reaction menu expires

### ISSUE THREAD

**Issue by flapjax** [flapjax/FlapJack-Cogs#40]
Suggested by del33t#6453on 06/28/2017

**Comment by aikaterna** [comment]
When Blizzard is looked at again for v3 and it gets back into a working state, I'm sure the UX will change because of us having menus available from Red's utils (or the d.py menus). Closing this as v2 support has ended but will keep it in mind if Blizzard gets some love.
