### ISSUE TITLE
[reactpoll] poll stop not working for admins

### ISSUE THREAD

**Issue by flapjax** [flapjax/FlapJack-Cogs#49]
Reported by Heaveria#6413 on 07/17/2017.

![](https://cdn.discordapp.com/attachments/133049553984159745/336523802445873162/unknown.png)
![](https://cdn.discordapp.com/attachments/293931421398073354/337026774464593920/unknown.png)

Due to admin check being commented out in old Red code.

**Comment by aikaterna** [comment]
This will not be fixed as v2 support has ended.
