### ISSUE TITLE
Wordcloud limit isn't respected

### ISSUE THREAD

**Issue by aikaterna** [flapjax/FlapJack-Cogs#55]
The limit should be 4000 words but you can use any number after the wordcloud command and the bot will try to fetch that number.

**Comment by flapjax** [comment]
After poking around in the discord.py source and the API server, there appears to be no real limit to the number of messages you can attempt to get with `logs_from`. However I agree that we should set some sort of cap to limit API abuse. I settled on 10k messages as a reasonable upper bound. Values over this will be ignored, and the default will still be 4k. I'll close this for now, but if anyone has feedback feel free to continue to post here.
