### ISSUE TITLE
[spoiler] Feature Request: Spoiler Title

### ISSUE THREAD

**Issue by Deus-Rex** [flapjax/FlapJack-Cogs#62]
As it currently is, it's not clear what the message will spoil unless the user states in another message. To make it more obvious, and the plugin to be more thorough, it would be great if it was possible to include the subject of the spoiler to be included in the 'Mouseover to reveal spoiler' frame, or perhaps even on the line where it says 'User posted this spoiler:'.

An alternative would be to either have it output 'Mouseover to reveal GoT spoiler' or 'User posted this GoT spoiler'.  The syntax could be to use quotations to separate them, such as 

`[p]spoilers "GoT" "such and such dies"`

Of course, the actual implementation doesn't matter. Just providing an example of what I'm thinking of.
An alternative bot that provides this functionality, to give another example, is [this one](https://github.com/TimboKZ/discord-spoiler-bot).

**Comment by flapjax** [comment]
Good suggestion. I would like to implement it in a way that doesn't break the current behavior. (i.e. omitting the spoiler subject still works). I'll have to review how string arguments are parsed but I'm pretty sure this will work with quotation marks like your example.

**Comment by flapjax** [comment]
This is now implemented in the V3 version, see 5bb7c1f41307f3568eb1e3ace9326a9dc92aabc6.
