### ISSUE TITLE
Cryptoprice Broken: 'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by brownmike** [flapjax/FlapJack-Cogs#63]
```
[14/02/2018 21:46] ERROR red on_command_error 369: Exception in command 'cprice'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/syphrix/Red-DiscordBot/cogs/cryptoprice.py", line 50, in cprice
    text = self.make_table(results)
  File "/home/syphrix/Red-DiscordBot/cogs/cryptoprice.py", line 68, in make_table
    column.append(row.find("td", class_="percent-24h").get_text().strip())
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by skeith** [comment]
This is just an early assumption (I haven't investigated deeper), I think the website change its structure

**Comment by spithash** [comment]
See here: https://github.com/flapjax/FlapJack-Cogs/pull/64

**Comment by skeith** [comment]
@spithash thanks, I was right. Sorry I missed your PR
(in the middle of having breakfast)

**Comment by spithash** [comment]
No worries :)

**Comment by spithash** [comment]
hrm, it's hard to tell. Looks like an issue on the edit you did? I'm not quite sure, could you somehow provide the entire code to investigate the changes you made?

**Comment by spithash** [comment]
The one here works perfectly, like it used to https://github.com/spithash/FlapJack-Cogs/blob/master/cryptoprice/cryptoprice.py

**Comment by brownmike** [comment]
Apparently, I needed to restart Red entirely. What threw me off was the error message confirmed the fix was there and running. Not sure how that happens, but whatever. It's working now so thanks for the patch!

**Comment by spithash** [comment]
You are welcome :) 
Good to hear it worked for you.

**Comment by flapjax** [comment]
Thanks for the contribution! I'll review and merge as soon as I can.

**Comment by spithash** [comment]
Thank  you very much :+1:

**Comment by flapjax** [comment]
Fixed! :)
