### ISSUE TITLE
[v2 SmartReact] Addreact command with no arguments errors out

### ISSUE THREAD

**Issue by mina9999** [flapjax/FlapJack-Cogs#67]
also i think there is a bug  that cog cant show the help
![45673474567457](https://user-images.githubusercontent.com/28566705/36469474-920d5252-16fc-11e8-9869-39c8bd29c48b.png)
![sdfsdfasdgsdfg](https://user-images.githubusercontent.com/28566705/36469574-ea57cf32-16fc-11e8-8d3a-0a2c67ebf317.png)

**Comment by flapjax** [comment]
Thanks for reporting. I've not looked into animated emojis yet, but it's on my list!

**Comment by aikaterna** [comment]
Hi, this is resolved in c1781c3.
