### ISSUE TITLE
sfx not playing sounds

### ISSUE THREAD

**Issue by paulternate** [flapjax/FlapJack-Cogs#68]
First of all, love the cog. Thanks a bunch! 

Lately, it's not playing sounds and throwing the attached error. 
[sfx-error.txt](https://github.com/flapjax/FlapJack-Cogs/files/1813542/sfx-error.txt)

**Comment by flapjax** [comment]
This looks like an internet connectivity problem. Is it still happening? Is the core audio cog able to connect and play audio?

**Comment by paulternate** [comment]
Thanks for the response! It has _somewhat_ started working again. It seems to be intermittent. Sometimes the bot won't connect at all, sometimes it connects and plays the sound and is unable to leave the channel afterwards. 

I have recently been having some issues with my internet, so that is a very likely scenario, although the timing doesn't seem to match. Additionally, a reboot of Red seems to fix it, but only temporarily, so that is another reason to believe it's a connectivity issue. I'll do some more testing when it happens again and get back to you.

**Comment by flapjax** [comment]
Ok, thanks, keep us posted. In the past, people have reported that changing your server's region in server settings can help to alleviate problems connecting to channels and playing audio. Could be worth a try.

**Comment by paulternate** [comment]
Ok, after some more testing, the bot is still having intermittent issues, and I'm not sure what could be causing them. If it's a network issue, I'm not sure where to look or how to go about fixing it if I were able to find it. All I know is it started happening randomly. The bot is running on my server, on the same home network that I'm connecting to the Discord client on. I can RDP to my server to restart the bot and see the error messages. 

If there is any other info to provide, I'm happy to do so. 

![image](https://user-images.githubusercontent.com/27632860/37982332-2a1e8ddc-31a5-11e8-99c0-9286aa7b3c2e.png)

**Comment by flapjax** [comment]
Looks like you have the core Audio cog unloaded. Sfx requires it to be running. Try `[p]load audio`?

**Comment by paulternate** [comment]
Wow. Apologies for wasting your time. I intentionally disabled the audio cog a while back and since sfx was still playing, I assumed incorrectly. Sorry again. Thanks for the tip! Everything is good now. You're amazing!

**Comment by flapjax** [comment]
Oh no problem at all. Glad we figured it out!

**Comment by phildinh** [comment]
Sorry to re-open this but I got almost the exact same thing, meaning that the bot will connect and play the sound and it'll able to leave the channel but after that it'll rejoin the channel and stay silent without playing any audio.
Furthermore I get incosistent logs when this happens:

after a restart
`Task was destroyed but it is pending!
task: <Task pending coro=<Audio.disconnect_timer() running at /root/red/cogs/audio.py:2200> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_scheduler() running at /root/red/cogs/audio.py:2406> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.reload_monitor() running at /root/red/cogs/audio.py:2410> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.cache_manager() running at /root/red/cogs/audio.py:2149> wait_for=<Future pending cb=[Task._wakeup()]>>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f97ff16d438>`

sometimes this
`Parse error, at least 3 arguments were expected, only 1 given in string 'ogs.audio.ConnectTimeout: We timed out connecting to a voice channelTask was destroyed but it is pending!'`

sometimes a whole ffmpeg log
`stream #0:
  keyframe=1
  duration=0.026
  dts=1.567  pts=1.567
  size=627
[out_0_0 @ 0x5584adbeb9c0] EOF on sink link out_0_0:default.=1.54x
debug=1
No more output streams to write to, finishing.
size=     294kB time=00:00:01.56 bitrate=1536.0kbits/s speed=1.51x
video:0kB audio:294kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
Input file #0 (data/sfx/288396748454625280/ez.mp3):
  Input stream #0:0 (audio): 61 packets read (38243 bytes); 61 frames decoded (69167 samples);
  Total: 61 packets (38243 bytes) demuxed
Output file #0 (pipe:1):
  Output stream #0:0 (audio): 62 frames encoded (75284 samples); 62 packets muxed (301136 bytes);
  Total: 62 packets (301136 bytes) muxed
61 frames successfully decoded, 0 decoding errors
[AVIOContext @ 0x5584adbd95c0] Statistics: 0 seeks, 62 writeouts
[AVIOContext @ 0x5584adbde8c0] Statistics: 40052 bytes read, 0 seeks`

sometimes this (but it seems to not appear anymore)
`Enter command: <target>|all <time>|-1 <command>[ <argument>]

Parse error, at least 3 arguments were expected, only 1 given in string 'ordBot/cogs/sfx.py:130> exception=AttributeError("'NoneType' object has no attribute 'voice_client'",)>'`

and 99% of the time when the bot gets stuck in the VC without playing any audio, no errors are output at all.

**Comment by fididev** [comment]
After further debugging, it seems that the cog stops at this line when it doesn't play any audio: `vc = await self.bot.join_voice_channel(channel)`.

It doesn't even print the vc after that and it just plain stops there without any errors.

**Comment by fididev** [comment]
Seems like switching VPS provider fixed the solution. After countless of changed machines, OSes, factory resets, networking edits, opened and closed tickets, I switched to another provider and now the bot will connect and disconnect from VCs flawlessly.

**Comment by skeith** [comment]
@fididev for documentation purposes, what was your previous provider?

I have my hunch, was it hetzner ?
