### ISSUE TITLE
[ReactPoll] Support more than 9 options.

### ISSUE THREAD

**Issue by BraveLittleRoaster** [flapjax/FlapJack-Cogs#69]
I did the work for you here: 
https://github.com/BraveLittleRoaster/Roaster-Cogs/blob/master/alphapoll/alphapoll.py

If anyone needs more than 9 options, you can use this fork until FlapJack can update reactpoll.

**Comment by flapjax** [comment]
Hey, nice work. If you open a pull request with these changes, I will merge it in.

**Comment by aikaterna** [comment]
Considering Red v2 isn't really supported any more, I am closing this in the idea that the reactpoll cog we have for v3 now supports more than 9 options (and you can specify your own emojis to react with, not just 1-9).
