### ISSUE TITLE
gtts throws an error

### ISSUE THREAD

**Issue by HelmicNewciv** [flapjax/FlapJack-Cogs#7]
While the bot initially worked, I can no longer get it working, even after restarting each bot I have this running on or uninstalling and then reinstalling the plugin.  This is the error message that comes up when someone tries to use !gtts <text> whether or not they're in a channel:

`Error in command 'gtts' - AttributeError: 'NoneType' object has no attribute 'group'`

Just using !gtts by itself gives this, which is expected behavior:

`Error in command 'gtts' - Exception: No text to speak`

**Comment by ptoast** [comment]
Thanks for reporting this. I've not had access to my development stuff for a few days. I will see if I can duplicate this now.

**Comment by ptoast** [comment]
I'm not able to duplicate this. Could you please provide screenshots or copypastes of:

- The command being used and the bot's response.
- Full traceback of the error in your bot's console.

Thank you!

**Comment by HelmicNewciv** [comment]
Latest patch seems to fix this.  Works as expected.

**Comment by flapjax** [comment]
Thanks for catching this. It was a missing chat formatting import. It has been fixed with commit https://github.com/flapjax/FlapJack-Cogs/commit/47af5bab3832a2a469fb1b127698307b150f3918.

Also, consider transitioning to my new sfx cog. It includes a better implementation of gTTS.
