### ISSUE TITLE
[SFX] Can you change de [p]tts language with some sort of [p]set command?

### ISSUE THREAD

**Issue by pabloleban** [flapjax/FlapJack-Cogs#71]

**Comment by flapjax** [comment]
Sure, this is something fairly simple I had planned to implement. I will include it when the cog gets updated for Red v3.

**Comment by HelmicNewciv** [comment]
also espeak at some point please i need to be able to customize the voice so that it sounds like a very irritated bot spacing out its words every half second

**Comment by aikaterna** [comment]
SFX will not be created on this repo for v3. Another unapproved cog creator named baiumbg has taken over the sfx cog and you can find it by searching github or google for him or his repo. Closing this as this is a v2-related issue and v2 support has ended.
