### ISSUE TITLE
Msgvote, no reactions

### ISSUE THREAD

**Issue by evacfk** [flapjax/FlapJack-Cogs#98]
Msgvote is enabled in the channel, emotes are set. However nothing comes up when typing in  the channel.

**Comment by aikaterna** [comment]
Are you sure your bot has the permission to add reactions in that channel?

**Comment by aikaterna** [comment]
While looking through msgvote it may be that you're on Red 3.1.x and the cog hadn't been updated with the new listener decorator. I've added that in commit b5ccf75, please give it a try and see if it resolves this.
